INSERT INTO products (name, price, created_at) VALUES ('Panasonic', 800, NOW());
INSERT INTO products (name, price, created_at) VALUES ('Sony', 700, NOW());
INSERT INTO products (name, price, created_at) VALUES ('Apple', 1000, NOW());
INSERT INTO products (name, price, created_at) VALUES ('HP', 100, NOW());
INSERT INTO products (name, price, created_at) VALUES ('Adidas', 500, NOW());
INSERT INTO products (name, price, created_at) VALUES ('Reebok', 100, NOW());
INSERT INTO products (name, price, created_at) VALUES ('Archos', 300, NOW());
INSERT INTO products (name, price, created_at) VALUES ('Nokia', 200, NOW());
INSERT INTO products (name, price, created_at) VALUES ('Lego', 800, NOW());